### ISSUE TITLE
Vue3版本字典路由出现404错误

### ISSUE THREAD

**Issue by alpeak-long** [yangzongzhuan/RuoYi-Vue3#134]
路由路径：/system/dict-data/index/1

**Comment by myma911** [comment]
怎么解决呢

**Comment by joker-wei-j** [comment]
我也发现了这个问题，请问怎么解决

**Comment by myma911** [comment]
已经收到您的来信，我会尽快回复。关注Mr_艾伦微博http://weibo.com/u/1658162891

**Comment by alpeak-long** [comment]
应该是你路由中的name属性重复，或者路由中有重复的路由，比如，a/b/index与a/index/d就可能会冲突，注意名字和路径就好



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月08日 11:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) |

我也发现了这个问题，请问怎么解决

**Comment by joker-wei-j** [comment]
我重新定义了他的路径还是会出现404的状态

**Comment by joker-wei-j** [comment]
我重新定义了路径之后还是会出现404的状态，是怎么回事

**Comment by joker-wei-j** [comment]
> 应该是你路由中的name属性重复，或者路由中有重复的路由，比如，a/b/index与a/index/d就可能会冲突，注意名字和路径就好 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年03月08日 11:27 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) | 我也发现了这个问题，请问怎么解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

好的感谢，修改name属性后成功解决这个问题

**Comment by alpeak-long** [comment]
另外就是路由路径中尽量不要用出现过的路径中的单词，也会有可能出现路由失效，比如。a/b和b/c容易出现问题。另外路由不建议用index做路由的某个单词他和index.vue会冲突失效，比如data/index和data/index/index.vue(vue实际的路径)冲突



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月08日 14:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) |

应该是你路由中的name属性重复，或者路由中有重复的路由，比如，a/b/index与a/index/d就可能会冲突，注意名字和路径就好 | | @.*** | | @.*** |
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年03月08日 11:27 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) | 我也发现了这个问题，请问怎么解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

好的感谢，修改name属性后成功解决这个问题

**Comment by joker-wei-j** [comment]
明白了，感谢&nbsp;


魏云龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134)





 另外就是路由路径中尽量不要用出现过的路径中的单词，也会有可能出现路由失效，比如。a/b和b/c容易出现问题。另外路由不建议用index做路由的某个单词他和index.vue会冲突失效，比如data/index和data/index/index.vue(vue实际的路径)冲突
 
 
 
 | |
 ***@***.***
 |
 |
 ***@***.***
 |
 
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2023年03月08日 14:27 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;***@***.***&gt; |
 | 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) |
 
 应该是你路由中的name属性重复，或者路由中有重复的路由，比如，a/b/index与a/index/d就可能会冲突，注意名字和路径就好 | | @.*** | | @.*** |
 …
 ---- 回复的原邮件 ---- | 发件人 | @.&gt; | | 日期 | 2023年03月08日 11:27 | | 收件人 | @.&gt; | | 抄送至 | @.***@***.***&gt; | | 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) | 我也发现了这个问题，请问怎么解决 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
 
 好的感谢，修改name属性后成功解决这个问题

**Comment by alpeak-long** [comment]
路由名称name重复，或者是路由路径有重复单词，例如/data/index和data/index/index.vue或a/b和b/c



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月22日 13:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) |

怎么解决呢

**Comment by Emmpty** [comment]
这个还没修复吗  都好久了  这个3.0版本是不维护了吗？

**Comment by myma911** [comment]
已经收到您的来信，我会尽快回复。关注Mr_艾伦微博http://weibo.com/u/1658162891

**Comment by alpeak-long** [comment]
这个是路由名称有重复现象，取名字注意下就不会了，比如a/b和b/a/c就是重复的，在路由list里面就不会在添加。另外这个版本合并到另一个仓库里去了，也就是后台代码哪里



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月25日 17:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) |

这个还没修复吗 都好久了 这个3.0版本是不维护了吗？

**Comment by Emmpty** [comment]
治标不治本啊  到底是哪里导致的    不可能说  /a/b/c    /a/d/c  这样的路由 也判断成同一个吧    有一个同名都404，，新文档地址仓库地址是什么？？请问这个问题修复了吗

**Comment by alpeak-long** [comment]
路由里面有一个name属性，这个name不能重复



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月25日 17:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yangzongzhuan/RuoYi-Vue3] Vue3版本字典路由出现404错误 (Issue #134) |

治标不治本啊 到底是哪里导致的 不可能说 /a/b/c /a/d/c 这样的路由 也判断成同一个吧 有一个同名都404，，新文档地址仓库地址是什么？？请问这个问题修复了吗

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。

**Comment by myma911** [comment]
已经收到您的来信，我会尽快回复。关注Mr_艾伦微博http://weibo.com/u/1658162891

**Comment by SYLQW** [comment]
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/127100516/6bbcd36a-0d8e-444f-ba3d-16cd507e42ac)
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/127100516/ae06608f-d8b8-4116-a422-83dd90337679)
![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/127100516/da6eeedf-8d76-4b98-8d5f-7f3e7034f888)

**Comment by myma911** [comment]
已经收到您的来信，我会尽快回复。关注Mr_艾伦微博http://weibo.com/u/1658162891
